apiVersion: postgresql.baiju.dev/v1alpha1
kind: Database
metadata:
  name: demo-database
  namespace: demo-app
spec:
  image: docker.io/postgres
  imageName: postgres
  dbName: postgres
  bindingData: ['secret': 'something1', 'secret': 'something2', 'secret': 'something3']
